CREATE FUNCTION pgsp_format_yaml()
RETURNS void
AS 'MODULE_PATHNAME'
LANGUAGE C;

CREATE FUNCTION pgsp_format_xml()
RETURNS void
AS 'MODULE_PATHNAME'
LANGUAGE C;

REVOKE ALL ON FUNCTION pgsp_format_yaml() FROM PUBLIC;
REVOKE ALL ON FUNCTION pgsp_format_xml() FROM PUBLIC;
